### ISSUE TITLE
Make Banner for README.md

### ISSUE THREAD

**Issue by Punit-Choudhary** [Pragmatic-Programmers/ICC-Discord-Bot#4]
Need a Banner for README.md

The banner should describe the collaborative work of ICC & Pragmatic Programmer on this project by using the logo of ICC & Pragmatic Programmer.

**Todo:**
- [x] Assign issue to someone
- [x] Provide logos and theme

Discuss in discord server: https://discord.gg/bM9Wy6Yzn2

**Comment by ibhavika** [comment]
I'm willing
