### ISSUE TITLE
Make logo for Bot

### ISSUE THREAD

**Issue by Punit-Choudhary** [Pragmatic-Programmers/ICC-Discord-Bot#5]
Need a Logo for ICC-Discord-Bot

The Bot's logo should describe the collaborative work of ICC & Pragmatic Programmer on this project by using the logo of ICC & Pragmatic Programmer.

**Todo:**
- [x] Assign issue to someone
- [x] Provide logos and theme

Discuss in discord server: https://discord.gg/bM9Wy6Yzn2

**Comment by Steffanic** [comment]
I'd be interested in taking this issue. I joined the discord and I see the pragmatic programmer logo, but I am not sure about the ICC logo. Can you provide a link?

**Comment by Punit-Choudhary** [comment]
Hey @Steffanic 👋 
Thank you for showing interest!
[ICC](https://icc-techsahead.netlify.app/) is an Open Source Competition which is being conducted by TechsAhead.
In order to contribute to this repo, you have to sign up on [Devfolio](https://icc.devfolio.co/) with referral code: ICC016
Let me know once you're done.
Thanks 😃

**Comment by ibhavika** [comment]
I'd like to do this.

**Comment by Punit-Choudhary** [comment]
Assigned to you 😃
Create `assets/img` folder(s) and upload logo there.
waiting for your PR 😸

**Comment by Punit-Choudhary** [comment]
Resolved by @ibhavika in #7
